version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: tonydb
      MYSQL_USER: tony
      MYSQL_PASSWORD: tonypw
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"