
DROP TABLE IF EXISTS demo;
CREATE TABLE demo (
  id INT NOT NULL AUTO_INCREMENT,
  foo VARCHAR(100) NOT NULL,
  bar VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));
  
DROP TABLE IF EXISTS Course;
CREATE TABLE Course (
  courseId INT NOT NULL AUTO_INCREMENT,
  schoolId INT NOT NULL,
  subject VARCHAR(100) NOT NULL,
  room VARCHAR(100) NOT NULL,
  PRIMARY KEY (courseId));